;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
+GameplayTagList=(Tag="MyRPGGame",DevComment="Stats Designer namespace root")
+GameplayTagList=(Tag="MyRPGGame.Stats",DevComment="Stats root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute",DevComment="Attributes root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat",DevComment="Stats root")
+GameplayTagList=(Tag="MyRPGGame.Formula",DevComment="Formula root")
+GameplayTagList=(Tag="MyRPGGame.Table",DevComment="Table root")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect",DevComment="Status Effect root")
+GameplayTagList=(Tag="MyRPGGame.Reward",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Reward.EXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute.HP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute.MP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Exp",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.EXPReward",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Level",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.Attack.BasicAttackDamage",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Character.RPGEnemy",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Character.RPGPlayer",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.StatCalculation.Default",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.BaseFlat",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.BasePercent",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.FinalFlat",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.FinalPercent",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerLevel.Level",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerLevel.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerLevel.MaxEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Table.Level.ExperienceProgression",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.EXPReward",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.Bleeding",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.ArmorBreak",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.Regeneration",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.PowerBlessing",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Weapon.IronSword",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Weapon.LevelingBlade",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.Equipment.LevelingBladeAttack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Armor.IronweaveArmor",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Helmet.TacticianHelm",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Boots.WandererBoots",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.ManaRegeneration",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Table.Enemy.EnemyProgression",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MoveSpeed",DevComment="")

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="MyRPGGame.Reward.Experience",NewTagName="MyRPGGame.Reward.EXP")
+GameplayTagList=(Tag="MyRPGGame",DevComment="Stats Designer namespace root")
+GameplayTagList=(Tag="MyRPGGame.Character.RPGEnemy",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Character.RPGPlayer",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula",DevComment="Formula root")
+GameplayTagList=(Tag="MyRPGGame.Formula.Attack.BasicAttackDamage",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.EXPReward",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.EnemyStat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.Equipment.LevelingBladeAttack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerLevel.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerLevel.Level",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerLevel.MaxEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Formula.PlayerStat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Armor.IronweaveArmor",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Boots.WandererBoots",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Helmet.TacticianHelm",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Weapon.IronSword",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Inventory.Equipment.Weapon.LevelingBlade",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.BaseFlat",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.BasePercent",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.FinalFlat",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Modifier.FinalPercent",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Reward",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Reward.EXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.StatCalculation.Default",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats",DevComment="Stats root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute",DevComment="Attributes root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute.HP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Attribute.MP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat",DevComment="Stats root")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Attack",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.CurrentEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Defense",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Exp",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.EXPReward",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.Level",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.ManaRegeneration",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxEXP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxHP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MaxMP",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.Stat.MoveSpeed",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect",DevComment="Status Effect root")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.ArmorBreak",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.Bleeding",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.ChoGathFeast",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.PowerBlessing",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Stats.StatusEffect.Regeneration",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Table",DevComment="Table root")
+GameplayTagList=(Tag="MyRPGGame.Table.Enemy.EnemyProgression",DevComment="")
+GameplayTagList=(Tag="MyRPGGame.Table.Level.ExperienceProgression",DevComment="")


